- name: Create castReactor dir if not exists
  ansible.builtin.command: mkdir -p /home/{{ user }}/castReactor

- name: Copy open box autostart
  ansible.builtin.command: cp openbox/autostart /etc/xdg/openbox/

- name: create local autostart openbox
  ansible.builtin.command: mkdir -p /home/{{ user }}/.config/openbox

- name: copy autostart local script
  ansible.builtin.command: cp openbox/autostartlocal /home/{{ user }}/.config/openbox/autostart

- name: copy startOpenBox local script
  ansible.builtin.command: cp openbox/startOpenBox.sh /home/{{ user }}/castReactor

- name: change owner auto start
  ansible.builtin.command: sudo chown -R {{ user }}:{{ user }} /home/{{ user }}/.config

- name: make startOpenBox.sh executable
  ansible.builtin.file:
    path: /home/{{ user }}/castReactor/startOpenBox.sh
    state: touch
    mode: u+x,g+x,o+x

- name: add .bash_profile to start X in console mode
  ansible.builtin.command: cp bash/.bash_profile /home/{{ user }}
  when: files_in_homeFolder.stdout.find('.bash_profile') == -1

- name: change .bash_profile owner
  ansible.builtin.command: sudo chown {{ user }}:{{ user }} /home/{{ user }}/.bash_profile
  when: files_in_homeFolder.stdout.find('.bash_profile') == -1

- name: add .xinitrc to start X with open box
  ansible.builtin.command: cp xinit/.xinitrc /home/{{ user }}
  when: files_in_homeFolder.stdout.find('.xinitrc') == -1

- name: change .xinitrc owner
  ansible.builtin.command: sudo chown {{ user }}:{{ user }} /home/{{ user }}/.xinitrc
  when: files_in_homeFolder.stdout.find('.xinitrc') == -1
