---
- hosts: localhost
  pre_tasks:
    - name: update repository
      apt:
        update_cache: yes

  tasks:
    - import_tasks: ansibleTasks/packages.yml
    - import_tasks: ansibleTasks/syncTotemFiles.yml
